version: "3"

services:

################################## pihole -> Werbeblocker
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'SUPERGEHEIMESPASSWORD'
      DNS1: '9.9.9.9'
      DNS2: '149.112.112.112'
      IPv6: 'true'
    #ServerIP: --net=host mode requires
    # Volumes store your data between container upgrades
    volumes:
       - '/mnt/dockerconf/pihole/etc-pihole/:/etc/pihole/'
       - '/mnt/dockerconf/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 9.9.9.9
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    hostname: pi.hole
################################## watchtower -> Docker auto updater

  watchtower:
      container_name: watchtower
      image: containrrr/watchtower
      command: --schedule '0 0 0 * * *' --cleanup true watchtower pihole unifi-controller heimdall homebridge
      environment:
        - TZ='Europe/Berlin'
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=<"EMAIL_FROM">
        - WATCHTOWER_NOTIFICATION_EMAIL_TO=<"EMAIL_TO">
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=<"EMAIL_SERVER">
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=<"SERVER_USER">
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<"SUPERGEHEIMESPASSWORD">
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always

################################## homebridge 
  homebridge:
    image: oznu/homebridge:raspberry-pi
    restart: always
    network_mode: host
    volumes:
      - /mnt/dockerconf/homebridge:/homebridge
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8081

################################## unifi-controller
  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=512M #optional
    volumes:
      - /mnt/dockerconf/unifi/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514 #optional
    restart: unless-stopped

  ################################## heimdall -> Web Interface Manager
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/dockerconf/heimdall/config:/config
    ports:
      - 81:80
      - 444:443
    restart: unless-stopped
